name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Render
        run: render login --token ${{ secrets.RENDER_TOKEN }} 
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}

      - name: Deploy to Render
        run: render up
