name: Continuous Integration
#DevOps ,test and release,deploy your code in small steps so basically,your able to know if there are issues before certain triggers like before merging
#test deploy built in package.json -- scripts are automated
# what triggers the integration ,its triggered on pull requests merged to the main branch
# ci/cd - executes some instructed tasks.
#runner is a build instance which is used to run the jobs over multiple machines and send the results

on:
  pull_request:
    branches: [main]

env:
  DATABASE_URL:postgresql://postgres:vuni@localhost:5432/quotesdb?schema=public    

#Runs on a linux container in the cloud, you must tell the container what to do.
#The steps will either pass or fail but bad code is avoided
#ubuntu is the host / computer

jobs:
  test:
    runs-on: ubuntu latest

    services:
      postgres:
        image: 
          postgres:14-alpine
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: vuni
            POSTGRES_DB: quotesdb
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready    
            --health-interval 10s    
            --health-timeout 5s    
            --health-retires 5s    

      steps:
        - name: checkout code into runner
          uses: actions/checkout@v2

        - name: setup node on the runner
          uses: actions/setup-node@v1
          with:
            node-version:14 

        - name: Install project dependencies
          uses: npm ci

        - name: Run database migration files
          uses: npm run db-migrate

        - name: Run unit tests
          run: npm test





